### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by necrose99**
added in some entropy code found in my old fork, 
its not much but pushing it back upstream will add a bit more value , as we wont have to maintain as much.

### CODE REVIEW

**Comment by BlackNoxis** [comment]
We have our separate branch

**Comment by necrose99** [comment]
no biggy , this was just the patch i made to back end feel free to abuse.

**Comment by BlackNoxis** [comment]
Freely :)

**Comment by necrose99** [comment]
https://github.com/necrose99/calamares/blob/master/src/modules/packages/main.py-entropy-add.diff
https://github.com/necrose99/calamares/blob/master/src/modules/packages/packages.conf.Entropy-add.diff
a few entropy related diff hacks ,

**Comment by V3n3RiX** [comment]
I already added entropy support + backend tweaks + wip branding to our
branch...you can take a look and do a pull if you want...however, for
the moment I will not try to push my changes to upstream, not until
I'm sure it works...for that we need to write an ebuild and actually
see it at work...I would recommend being cautious on this, cause once
we push it upstream, we will HAVE TO maintain our code...we must be
sure it works first, nobody likes broken code...

**Comment by necrose99** [comment]
sweet , i'll take it for a drive.

**Pull request closed without merging**
